# This file was generated by Credo. Adjust as needed.
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "test/"],
        excluded: ["_build/", "deps/"]
      },
      strict: true,
      color: true,
      checks: [
        {Credo.Check.Readability.ModuleDoc, []},
        {Credo.Check.Readability.MaxLineLength, [priority: :low, max_length: 100]},
        {Credo.Check.Readability.VariableNames, []},
        {Credo.Check.Readability.AliasOrder, []},
        {Credo.Check.Readability.LargeNumbers, []},
        {Credo.Check.Design.TagTODO, [exit_status: 0]},
        {Credo.Check.Design.TagFIXME, [exit_status: 0]},
        {Credo.Check.Warning.UnusedEnumOperation, []},
        {Credo.Check.Warning.UnusedFileOperation, []},
        {Credo.Check.Warning.UnusedKeywordOperation, []},
        {Credo.Check.Warning.UnusedListOperation, []},
        {Credo.Check.Warning.UnusedPathOperation, []},
        {Credo.Check.Warning.UnusedRegexOperation, []},
        {Credo.Check.Warning.OperationOnSameValues, []},
        {Credo.Check.Refactor.CyclomaticComplexity, [max_complexity: 10]},
        {Credo.Check.Refactor.Nesting, [max_nesting: 2]}
      ]
    }
  ]
}
